# Dependencies
#markdown:         redcarpet
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Nikhil Soni
tagline: <a href="https://twitter.com/krsoninikhil">@krsoninikhil</a>
description:
url: https://krsoninikhil.github.io
comments: true

author:
  name: Nikhil Soni
  url: https://twitter.com/krsoninikhil

contact:
  email: krsoninikhil@gmail.com
  twitter: https://twitter.com/krsoninikhil
  angellist: https://angel.co/krsoninikhil
  aboutme: https://about.me/krsoninikhil
  instagram: https://wwww.instagram.com/krsoninikhil

links:
  source: https://github.com/krsoninikhil/krsoninikhil.github.io
  github: https://github.com/krsoninikhil
  resume: https://goo.gl/My8bsV
  linkedin: https://www.linkedin.com/in/krsoninikhil/

paginate: 5
gems:
 - jekyll-paginate
